version: '3.8'

services:
  web:
    build:
      context: ./redis_demo
      dockerfile: Dockerfile
    command: ./server_setup.sh
    volumes:
      - ./redis_demo:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SUPERUSER_PASSWORD=adminpassword

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
